# Generated by Django 6.0.4 on 2026-04-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'siteconfig_cmspage',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'siteconfig_emailsetting',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ElectroHub', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('header_text', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=16)),
                ('secondary_color', models.CharField(default='#4f46e5', max_length=16)),
                ('button_color', models.CharField(default='#2563eb', max_length=16)),
                ('link_color', models.CharField(default='#2563eb', max_length=16)),
                ('background_color', models.CharField(default='#ffffff', max_length=16)),
                ('footer_color', models.CharField(default='#0f172a', max_length=16)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'siteconfig_sitesetting',
            },
        ),
    ]
