# Generated by Django 6.0.4 on 2026-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/hero/"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/banner/"),
        ),
    ]
