# Generated by Django 6.0.4 on 2026-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_sitesetting_hero_image_and_homepage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usd_to_bdt_rate',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
    ]
