# Generated by Django 6.0.4 on 2026-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_sitesetting_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Optional full-width hero background (behind text).', null=True, upload_to='site/hero_bg/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='Next Gen Technology', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_cta_primary_label',
            field=models.CharField(blank=True, default='Shop Collection', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_cta_primary_url',
            field=models.CharField(blank=True, default='/products', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_cta_secondary_label',
            field=models.CharField(blank=True, default='Explore Categories', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_cta_secondary_url',
            field=models.CharField(blank=True, default='/products', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(blank=True, default='Experience the next evolution of gadgets. Precision engineered, beautifully designed, and built for the modern world.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, default='The Future', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_highlight',
            field=models.CharField(blank=True, default='of Innovation.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='promo_cta_label',
            field=models.CharField(blank=True, default='Shop Audio Deals', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='promo_cta_url',
            field=models.CharField(blank=True, default='/products?category=Audio', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='promo_description',
            field=models.TextField(blank=True, default='Get up to 30% off on all Sony and Bose headphones this week. Experience audio like never before.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='promo_title',
            field=models.CharField(blank=True, default='Immersive', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='promo_title_highlight',
            field=models.CharField(blank=True, default='Sound Experience.', max_length=255),
        ),
    ]
