# Generated by Django 6.0.4 on 2026-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_days', models.PositiveSmallIntegerField(default=3)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'orders_shippingzone',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
